Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using branding.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using branding.Models;

namespace branding.Controllers
{
    public class ConsultaController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public ConsultaController(ILogger<HomeController> logger,  ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }       
         public IActionResult consultas()
         {
            return View();
        }
        [HttpPost]
        public IActionResult consultas(Consulta c)
        {
            if(ModelState.IsValid){
                _context.Add(c);
                _context.SaveChanges();
                return RedirectToAction("confirmacion");
            }
            return View(c);
        } 
        public IActionResult confirmacion()
        {
            return View();
        }

        public IActionResult ListarConsultas(){
            var conssultas = _context.Consultas.ToList();
            return View(conssultas);

        }

        }
    }

Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using branding.Data;
using branding.Models;

namespace branding.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Producto
        public async Task<IActionResult> Index()
        {
            return View(await _context.Producto.ToListAsync());
        }

        // GET: Producto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .FirstOrDefaultAsync(m => m.ID == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Producto/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Producto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Price,ImagenName,Status")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Producto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Price,ImagenName,Status")] Producto producto)
        {
            if (id != producto.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .FirstOrDefaultAsync(m => m.ID == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producto = await _context.Producto.FindAsync(id);
            _context.Producto.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
            return _context.Producto.Any(e => e.ID == id);
        }
    }
}

Controllers/ProformaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using branding.Data;
using branding.Models;
using Microsoft.AspNetCore.Identity;

namespace branding.Controllers
{
    public class ProformaController : Controller
    {
        private readonly ApplicationDbContext _context;
         private readonly UserManager<IdentityUser> _userManager;

        public ProformaController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Proforma
        public async Task<IActionResult> Index()
        {

            var userID = _userManager.GetUserName(User);
            var items = from o in _context.Proforma select o;
            items = items.
                Include(p => p.Producto).
                Where(s => s.UserID.Equals(userID));
            
            return View(await items.ToListAsync());
        }

        // GET: Proforma/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proforma = await _context.Proforma
                .Include(p => p.Producto)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (proforma == null)
            {
                return NotFound();
            }

            return View(proforma);
        }

        // GET: Proforma/Create
        public IActionResult Create()
        {
            ViewData["ProductoID"] = new SelectList(_context.Producto, "ID", "ID");
            return View();
        }

        // POST: Proforma/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,UserID,Price,ProductoID")] Proforma proforma)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proforma);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductoID"] = new SelectList(_context.Producto, "ID", "ID", proforma.ProductoID);
            return View(proforma);
        }

        // GET: Proforma/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proforma = await _context.Proforma.FindAsync(id);
            if (proforma == null)
            {
                return NotFound();
            }
            ViewData["ProductoID"] = new SelectList(_context.Producto, "ID", "ID", proforma.ProductoID);
            return View(proforma);
        }

        // POST: Proforma/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,UserID,Price,ProductoID")] Proforma proforma)
        {
            if (id != proforma.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proforma);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProformaExists(proforma.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductoID"] = new SelectList(_context.Producto, "ID", "ID", proforma.ProductoID);
            return View(proforma);
        }

        // GET: Proforma/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proforma = await _context.Proforma
                .Include(p => p.Producto)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (proforma == null)
            {
                return NotFound();
            }

            return View(proforma);
        }

        // POST: Proforma/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proforma = await _context.Proforma.FindAsync(id);
            _context.Proforma.Remove(proforma);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProformaExists(int id)
        {
            return _context.Proforma.Any(e => e.ID == id);
        }
    }
}

Controllers/QuienesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;


namespace branding.Controllers 
{
    public class QuienesController : Controller
    {
     private readonly ILogger<HomeController> _logger;

        public QuienesController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }       
        public IActionResult Somos()
        {
            return View();
        }

        }
    }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Andrómeda</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/style.css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link href="~/lib/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/lib/boxicons/css/boxicons.min.css" rel="stylesheet">
</head>
<body>

  
    <header>
        <div class="menu-principal">

       
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-0">
            <div class="container">
             
                           
                <a class="navbar-brand text-whitee" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/alfalogo.png" width="210" height="75"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        

                           <li class="nav-item">
                        </li> 
                            <a class="nav-link text-white"  asp-area="" asp-controller="Quienes" asp-action="Somos">QUIENES SOMOS </a>

                                           <li class="nav-item">
                        </li>
                            <a class="nav-link text-white" asp-area="" asp-controller="Portafolio" asp-action="portafolio"> PLANES DE INVERSIÓN</a>
                    
     
                        <partial name="_MenuPartial" />  
                     

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        
        </div>


        
    </header>

    
    <div >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>        
    @await RenderSectionAsync("Scripts", required: false)
</body>



<style>
.btn-whatsapp {
       display:block;
       width:45px;
       height:px;
       color:#fff;
       position: fixed;
       right:20px;
       bottom:20px;
       border-radius:50%;
       line-height:45px;
       text-align:center;
       z-index:999;
}
</style>
<div class="btn-whatsapp">
<a href="https://api.whatsapp.com/send?phone=916080836" target="_blank">
<img src="https://i.ibb.co/kqBsK2f/w2.png" alt="">
</a>
</div>




</html>
  <footer id="footer">
    <div class="footer-top">
      <div class="container" data-aos="fade-up">
        <div class="row  justify-content-center">
          <div class="col-lg-6">
            
            <h3>ANDRÓMEDA</h3>
            <p>Nuestras Redes Sociales</p>
          </div>
        </div>
        <div class="social-links">
          
          <a href="https://www.facebook.com/andromedabursatilcapital/" class="facebook" target="_blank"><i class="bx bxl-facebook"></i></a>
          <a href="https://www.instagram.com/andromedabursatilcapital/?igshid=YmMyMTA2M2Y%3D" class="instagram" target="_blank"><i class="bx bxl-instagram"></i></a>
          <a href="https://www.youtube.com/channel/UC0VA82FUIrB63PUGLng5UAQ" class="youtube" target="_blank"><i class="bx bxl-youtube" ></i></a>
          


         </div>
         

    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy;ANDRÓMEDA FONDO DE INVERSIÓN | Todos los derechos reservados. 
      </div>
      <div class="credits">
        Contacto (+51) Cel:916080836 - Cel:992668973

      </div>
    </div>
  </footer>

Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
@if (SignInManager.IsSignedIn(User))
{
     @if(UserManager.GetUserName(User).Equals("diegodsqs3@gmail.com")){
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Producto" asp-action="Index"> Agregar Producto</a>
        </li> 
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Proforma" asp-action="Index">Carrito</a>
        </li> 
        <li class="nav-item">
        <a class="nav-link text-white"  asp-area="" asp-controller="Consulta" asp-action="ListarConsultas">Ver Consultas</a>
        </li>
    }else
    {
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Proforma" asp-action="Index">Carrito</a>
        </li> 
    }
}
</ul>